spring: 
  application: 
    name: country-client 
server: 
  port: 9080
info:
  description: Country-Client-Hello App
  name: Hello Country with Discovery

eureka: 
  client: 
    serviceUrl: 
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka} 
  instance: 
    hostname: localhost 
    preferIpAddress: true
    status-page-url-path: http://${eureka.instance.hostname}:${server.port}/hello 
    health-check-url: http://${eureka.instance.hostname}:${server.port}/health 
    home-page-url: http://${eureka.instance.hostname}:${server.port}/
  register-with-eureka: false
  fetch-registry: false
